name: Terraform CVE Scans

permissions:
  security-events: write

on:
  push:
      branches: [main]
  pull_request:
      branches: [main]

jobs:
  tfsec_scan:
    name: TFSec Scan
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install TFSec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Run tfsec scan and generate SARIF report
        run: tfsec ./backend/infrastructure --format sarif --out tfsec.sarif

      - name: Upload tfsec SARIF report to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec.sarif

  checkov_scan:
    name: Checkov Scan
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Checkov scan for Terraform
        uses: bridgecrewio/checkov-action@v12
        with:
          framework: terraform
          directory: ./backend/infrastructure
          quiet: true
          output_format: cli,sarif
          output_file_path: checkov_terraform.sarif
          soft_fail: true

      - name: Upload Terraform Checkov SARIF report to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov_terraform.sarif

      - name: Run Checkov scan for NextJS
        uses: bridgecrewio/checkov-action@v12
        with:
          framework: nextjs
          directory: ./frontend
          quiet: true
          output_format: cli,sarif
          output_file_path: checkov_nextjs.sarif
          soft_fail: true

      - name: Upload NextJS Checkov SARIF report to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov_nextjs.sarif