name: Generate Terraform docs

on:
    push:
      branches: [main]
    pull_request:
      branches: [main]

permissions:
  contents: write

jobs:
  generate-tfdocs:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      
    - name: Render terraform docs for environment-stages
      uses: terraform-docs/gh-actions@v1.4.1
      with:
        working-dir: ./backend/infrastructure/environments/
        recursive: true
        recursive-path: stage
        output-method: replace
        git-push: true

    - name: Render terraform docs for modules
      uses: terraform-docs/gh-actions@v1.4.1
      with:
        working-dir: ./backend/infrastructure/
        recursive: true
        recursive-path: modules
        output-method: replace
        git-push: true